version: '3'
services:
    #PostgreSQL Users Database
    db-users:
        container_name: db-users
        image: postgres:15.2
        restart: unless-stopped
        environment:
        - POSTGRES_DB=ms_users
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - '5431:5431'
        expose:
          - 5431
        command: -p 5431
        networks:
        - ms-network
    #MongoDB Posts Database
    db-posts:
        container_name: db-posts
        image: mongo:5.0.14
        restart: unless-stopped
        environment:
        - MONGO_INITDB_DATABASE=ms_posts
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
        ports:
        - '27018:27018'
        expose:
          - 27018
        command: --port 27018
        networks:
        - ms-network
    #MongoDB Comments Database
    db-comments:
        container_name: db-comments
        image: mongo:5.0.14
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=ms_comments
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
        ports:
            - '27019:27019'
        expose:
            - 27019
        command: --port 27019
        networks:
            - ms-network
    #Neo4j Social Graph Database
    db-social:
        container_name: db-social
        image: neo4j:4.3.6
        restart: unless-stopped
        environment:
            - NEO4J_AUTH=neo4j/pas4j
        ports:
            - '7687:7687'
            - '7474:7474'
        expose:
            - 7687
            - 7474
        networks:
            - ms-network
#Network
networks:
    ms-network:
        driver: bridge