server:
  port: 8080

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes: # Routes for all services
          - id: users-service
            uri: lb://ms-users
            predicates:
              - Path=/users-service/**
          - id: posts-service
            uri: lb://ms-posts
            predicates:
              - Path=/posts-service/**
          - id: comments-service
            uri: lb://ms-comments
            predicates:
              - Path=/comments-service/**
          - id: social-service
            uri: lb://ms-social
            predicates:
              - Path=/social-service/**
