server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes: # Routes for all services
          - id: users-service
            uri: http://localhost:8081
            predicates:
              - Path=/users-service/**
          - id: posts-service
            uri: http://localhost:8082
            predicates:
              - Path=/posts-service/**
          - id: comments-service
            uri: http://localhost:8083
            predicates:
              - Path=/comments-service/**
          - id: social-service
            uri: http://localhost:8084
            predicates:
              - Path=/social-service/**
